name: network_inspector
description: Http inspector / logger for Dio and Http package. This package would allow you to log every Http request, response, and error from Dio & Http.
version: 1.1.1
homepage: https://github.com/Meruya-Techhnology/network_inspector

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  dio: ^5.1.0
  sqflite: ^2.2.6
  provider: ^6.0.5
  intl: ^0.19.0
  analyzer: ^6.2.0
  collection: ^1.17.2
  share_plus: ^9.0.0
  web_socket_client: ^0.1.4
  get_it: ^7.7.0
  network_info_plus: ^3.0.3
  device_info_plus: ^8.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/json/
