name: Network Inspector
on: [push]
jobs:
  Repository-Checker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ†™ Event :" ${{ github.event_name }}
      - run: echo "ğŸ¡ Branch :" ${{ github.ref_name }}
      - run: echo "ğŸ§‘ğŸ»â€ğŸ’» Owner :" ${{ github.user }}
      - run: echo "ğŸ”¢ Run number :" ${{ github.run_number }}
      - run: echo "ğŸ“ˆ Total run attempt :" ${{ github.run_attempt }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "âœ… Repository cloned successfully"
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -la
      - run: echo "ğŸ This job is finished"